version: '3'
services:
  notebook:
    build: .
    image: sjawhar/focus-stacking
    container_name: focus-stacking
    volumes:
      - "./:/home/jovyan/work"
    ports:
      - "8888:8888"
    command:
      - "start-notebook.sh"
      - "--NotebookApp.token=''"
      - "--NotebookApp.iopub_data_rate_limit=10000000000"